version: '3.7'
services:
    router:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./router
        depends_on:
            - node-api
            - java-api
        ports:
            - 80:80

    postgres:
        restart: unless-stopped
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/queries:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_DEFAULT_PASSWORD}
        ports:
            - '${PG_ADMIN_PORT}:80'
        restart: unless-stopped

    node-api:
        restart: unless-stopped
        build:
            dockerfile: Dockerfile.dev
            context: './node-api'
        volumes:
            - /app/node_modules
            - ./node-api:/app
        environment:
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_HOST=${PG_HOST}
            - PG_PORT=${PG_PORT}
            - PG_DATABASE=${PG_DATABASE}
            - API_PORT=${NODE_API_PORT}
            - CHOKIDAR_USEPOLLING=true
        ports:
            - '${NODE_API_PORT}:${NODE_API_PORT}'

    java-api:
        restart: unless-stopped
        build:
            dockerfile: Dockerfile.dev
            context: './java-api'
        volumes:
            - ./java-api/build:/app
        environment:
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_HOST=${PG_HOST}
            - PG_PORT=${PG_PORT}
            - PG_DATABASE=${PG_DATABASE}
            - API_PORT=${JAVA_API_PORT}
            - CHOKIDAR_USEPOLLING=true
        ports:
            - '${JAVA_API_PORT}:${JAVA_API_PORT}'
        depends_on:
            - java-builder
        command: java -cp "/app/classes/java/main:/app/dependencies/*:/app/resources/main" com.secondlife.demo.DemoApplication

    java-builder:
        image: gradle:jdk11
        working_dir: /home/gradle/project
        volumes:
            - ./java-api/build:/home/gradle/project/build
            - ./java-api/src:/home/gradle/project/src
            - ./java-api/build.gradle:/home/gradle/project/build.gradle
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: gradle build -t -x test -x testClasses
